spring.application.name=MessBuddy

server.servlet.context-path=/api

server.port=3000

app.jwt.secret=dclucluster08lasumodb
app.jwt.expiration-millis=3600000

#spring.data.mongodb.uri=mongodb+srv://brijamandarshan:brijamandarshan323140@cluster0.yqzmy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.uri=mongodb+srv://brijmohan755:SBLG%402003@wonderlust.bdh7ipe.mongodb.net/MessBuddy?retryWrites=true&w=majority&appName=WonderLust
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreply.messbuddy@gmail.com
spring.mail.password=zjnp cdjt aciy hkkg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud_name=dj0tijp1d
cloudinary.api_key=784966276579723
cloudinary.api_secret=MEyLXYTHDWeVZnHQvisAxHd08MA
